platform :ios, '11.0'
use_frameworks!

target 'Bloc_Example' do
  pod 'RxSwift'
  pod 'Bloc', :path => '../'

  target 'Bloc_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
