platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'Bloc_Example' do
  pod 'RxSwift'
  pod 'Bloc', :path => '../'

  target 'Bloc_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
